---
- hosts: localhost
  connection: local
  gather_facts: no
  become: false

  pre_tasks:
    - name: 'Check current architecture'
      shell: uname -m
      register: architecture
    - name: 'Install gem packages'
      gem: name={{ item }} executable=~/.anyenv/envs/rbenv/shims/gem user_install=False
      with_items:
        - bundler
        - homesick
        - cocoapods
        - gisty
        - sigh
    - name: 'Update pip'
      pip: name=pip executable=~/.anyenv/envs/pyenv/shims/pip state=latest
    - name: 'Install python packages'
      pip: name={{ item }} executable=~/.anyenv/envs/pyenv/shims/pip extra_args="--user" state=latest
      with_items:
        - powerline-status
        - psutil
    - name: 'Install node packages'
      npm: name={{ item }} executable=~/.anyenv/envs/nodenv/shims/npm global=yes state=latest
      with_items:
        - js-beautify
        - git-fire
    - name: 'Tap homebrew repositories'
      homebrew_tap: tap={{ item }} state=present
      with_items: 
        - homebrew/cask
        - homebrew/cask-versions
        - homebrew/cask-fonts
        - homebrew-ffmpeg/ffmpeg
        - supistar/customs
    - name: 'Update Homebrew'
      command: brew update

  tasks:
    - name: 'Install Homebrew cask packages'
      homebrew_cask: name={{ item }}
      with_items:
        - xquartz
        - 1password
        - adobe-creative-cloud
        - alfred
        - android-sdk
        - android-platform-tools
        - android-ndk
        - android-studio
        - appcode
        - atok
        - autodesk-fusion360
        - burn
        - chromedriver
        - chromium
        - daisydisk
        - docker
        - dropbox
        - firefox
        - font-mplus
        - font-terminus
        - goland
        - google-chrome
        - hex-fiend
        - hhkb-professional-driver
        - intellij-idea
        - ios-console
        - iterm2
        - jetbrains-toolbox
        - karabiner-elements
        - homebrew/cask-drivers/kensington-trackball-works
        - kindle
        - makemkv
        - osxfuse
        - pycharm
        - quik
        - sdformatter
        - skitch
        - skype
        - slack
        - spotify
        - steam
        - sublime-text
        - unity-hub
        - vagrant
        - virtualbox
        - visual-studio-code
        - vivaldi
        - vlc
        - vmware-fusion
        - webstorm
        - xmind
        - zoomus
    - name: 'Install Homebrew packages (x86_64)'
      when: architecture.stdout == "x86_64"
      homebrew:
        state: latest
        name:
          - apktool
          - appledoc
          - arduino-cli
          - circleci
          - mas
          - packer
          - sshfs
          - terraform
          - terraformer
          - wine
          - winetricks
          - xctool
    - name: 'Install Homebrew packages'
      homebrew:
        state: latest
        name:
          - gcc
          - adns
          - ag
          - ant
          - ansible
          - autoconf
          - automake
          - awscli
          - blueutil
          - boost
          - carthage
          - cmake
          - coreutils
          - ctags
          - curl
          - doxygen
          - expat
          - faac
          - fswatch
          - git
          - git-flow
          - git-lfs
          - glib
          - gnu-sed
          - gnupg
          - go
          - gradle
          - highlight
          - httpie
          - hub
          - icu4c
          - imagemagick
          - ios-sim
          - iproute2mac
          - jq
          - jsdoc3
          - lame
          - libevent
          - libpng
          - libtool
          - libusb
          - libusb-compat
          - libxml2
          - libyaml
          - maven
          - macos-trash
          - nkf
          - peco
          - pkg-config
          - psutils
          - reattach-to-user-namespace
          - redis
          - rename
          - source-highlight
          - sqlite
          - swig
          - tig
          - tmux
          - tree
          - watch
          - wget
          - x264
          - xvid
          - yasm
          - yuicompressor
          - z
          - zeromq
          - zsh
          - zsh-completions
    - name: 'Add Java environments to jenv'
      shell: find /Library/Java/JavaVirtualMachines -d -name "Home" -print0 | xargs -0 -I% ~/.anyenv/envs/jenv/bin/jenv add % || true
    - name: 'Install Homebrew packages: homebrew-ffmpeg/ffmpeg/ffmpeg'
      homebrew: name=homebrew-ffmpeg/ffmpeg/ffmpeg state=latest install_options=with-fdk-aac
    - name: 'Clone dotfiles under home dir'
      command: homesick clone supistar/dotfiles
    - name: 'Pull homesick dotfiles'
      command: homesick pull dotfiles
    - name: 'Make symlinks to under home dir'
      command: homesick symlink dotfiles --force
    - name: 'Clone powerline fonts'
      unarchive:
        src: https://github.com/powerline/fonts/archive/master.zip
        dest: /tmp
        remote_src: yes
    - name: 'Install powerline fonts'
      command: sh /tmp/fonts-master/install.sh
    - name: 'Refresh fonts cache'
      command: fc-cache -vf
    - name: 'Delete temporary directory for powerline fonts'
      file: path=/tmp/fonts state=absent
    - name: 'mkdir Karabiner-Elements base dir'
      file: path="~/.config" state=directory
    - name: 'Karabiner: Make symlink of setting files'
      file: src={{ item }} dest="~/.config/{{ item | basename }}" state=link force=yes
      with_fileglob:
        - ~/.homesick/repos/dotfiles/applications/Karabiner-Elements/*
    - name: 'mkdir vim related directories'
      file: path={{ item }} state=directory
      notify: install neobundle
      with_items:
        - ~/.vim/backup
        - ~/.vim/bundle
        - ~/.vim/undo

  handlers:
    - name: 'install neobundle'
      command: git clone git://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim

