---
- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no

  pre_tasks:
    - name: 'Install gem packages'
      gem: name={{ item }} executable=~/.anyenv/envs/rbenv/shims/gem user_install=False
      with_items:
        - bundler
        - homesick
        - cocoapods
        - gisty
        - sigh
    - name: 'Update pip'
      pip: name=pip executable=~/.anyenv/envs/pyenv/shims/pip2.7 state=latest
    - name: 'Install python packages'
      pip: name={{ item }} executable=~/.anyenv/envs/pyenv/shims/pip2.7 extra_args="--user" state=latest
      with_items:
        - powerline-status
        - psutil
    - name: 'Install node packages'
      npm: name={{ item }} executable=~/.anyenv/envs/ndenv/shims/npm global=yes state=latest
      with_items:
        - js-beautify
        - git-fire
    - name: 'Tap homebrew repositories'
      homebrew_tap: tap={{ item }} state=present
      with_items: 
        - caskroom/cask
        - caskroom/versions
        - caskroom/homebrew-fonts
        - homebrew/versions
        - sanemat/font
        - supistar/customs
        - tkengo/highway
    - name: 'Update Homebrew'
      command: brew update

  tasks:
    - name: 'Install Homebrew cask packages'
      homebrew_cask: name={{ item }}
      with_items:
        - xquartz
        - java8
        - 1password6
        - adobe-air
        - adobe-creative-cloud
        - alfred
        - android-sdk
        - android-ndk
        - android-studio
        - appcode
        - burn
        - caffeine
        - chromedriver
        - chromium
        - cooviewer
        - daisydisk
        - docker
        - dropbox
        - duet
        - firefox
        - font-m-plus
        - font-terminus
        - google-chrome
        - hhkb-professional-driver
        - intellij-idea
        - ios-console
        - iterm2
        - jetbrains-toolbox
        - karabiner-elements
        - kensington-trackball-works
        - kindle
        - limechat
        - macvim
        - makemkv
        - mono-mdk
        - pycharm
        - quik
        - sdformatter
        - skitch
        - skype
        - slack
        - spotify
        - sqlitebrowser
        - steam
        - sublime-text
        - vagrant
        - virtualbox
        - visual-studio-code
        - vivaldi
        - vlc
        - vmware-fusion
        - webstorm
        - xamarin-studio
        - xmind
    - name: 'Install Homebrew packages'
      homebrew: name={{ item }} state=latest
      with_items:
        - gcc
        - ant
        - ansible
        - apktool
        - appledoc
        - autoconf
        - automake
        - awscli
        - blueutil
        - boost
        - carthage
        - cmake
        - ctags
        - curl
        - doxygen
        - expat
        - faac
        - fswatch
        - git
        - git-flow
        - gnupg
        - go
        - gradle
        - heroku
        - highlight
        - highway
        - httpie
        - hub
        - icu4c
        - imagemagick
        - ino
        - ios-sim
        - iproute2mac
        - jq
        - jsdoc3
        - lame
        - libevent
        - libpng
        - libtool
        - libusb
        - libusb-compat
        - libxml2
        - libyaml
        - mas
        - maven
        - nkf
        - peco
        - phantomjs
        - pkg-config
        - psutils
        - reattach-to-user-namespace
        - redis
        - rmtrash
        - source-highlight
        - sqlite
        - swig
        - tig
        - tmux
        - tree
        - watch
        - wget
        - wine
        - winetricks
        - x264
        - xctool
        - xvid
        - yasm
        - yuicompressor
        - z
        - zeromq
        - zsh
        - zsh-completions
    - name: 'Install Homebrew packages: ffmpeg'
      homebrew: name=ffmpeg state=latest install_options=with-faac
    - name: 'Install Homebrew packages: ricty'
      homebrew: name=ricty state=latest install_options=powerline,vim-powerline
    - name: 'Clone dotfiles under home dir'
      command: homesick clone supistar/dotfiles
    - name: 'Pull homesick dotfiles'
      command: homesick pull dotfiles
    - name: 'Make symlinks to under home dir'
      command: homesick symlink dotfiles --force
    - name: 'Copy Ricty fonts'
      shell: cp -f /usr/local/opt/ricty/share/fonts/Ricty*.ttf ~/Library/Fonts/
    - name: 'Clone powerline fonts'
      unarchive:
        src: https://github.com/powerline/fonts/archive/master.zip
        dest: /tmp
        remote_src: yes
    - name: 'Install powerline fonts'
      command: sh /tmp/fonts-master/install.sh
    - name: 'Refresh fonts cache'
      command: fc-cache -vf
    - name: 'Delete temporary directory for powerline fonts'
      file: path=/tmp/fonts state=absent
    - name: 'mkdir Karabiner dir'
      file: path="~/Library/Application Support/Karabiner" state=directory
    - name: 'Karabiner: Make symlink of setting files'
      file: src={{ item }} dest="~/Library/Application Support/Karabiner/{{ item | basename }}" state=link force=yes
      with_fileglob:
        - ~/.homesick/repos/dotfiles/applications/Karabiner/*
    - name: 'mkdir vim related directories'
      file: path={{ item }} state=directory
      notify: install neobundle
      with_items:
        - ~/.vim/backup
        - ~/.vim/bundle
        - ~/.vim/undo

  handlers:
    - name: 'install neobundle'
      command: git clone git://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim

