---
- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no

  pre_tasks:
    - name: 'gem: install bundler'
      gem: name=bundler executable=~/.anyenv/envs/rbenv/shims/gem user_install=False
    - name: 'gem: install homesick'
      gem: name=homesick executable=~/.anyenv/envs/rbenv/shims/gem user_install=False
    - name: 'gem: install cocoapods'
      gem: name=cocoapods executable=~/.anyenv/envs/rbenv/shims/gem user_install=False
    - name: 'gem: install gisty'
      gem: name=gisty executable=~/.anyenv/envs/rbenv/shims/gem user_install=False
    - name: 'pip: update pip'
      command: ~/.anyenv/envs/pyenv/shims/pip2.7 install --upgrade pip
    - name: 'pip: install powerline'
      command: ~/.anyenv/envs/pyenv/shims/pip2.7 install --user powerline-status
    - name: 'pip: install psutil'
      command: ~/.anyenv/envs/pyenv/shims/pip2.7 install --user psutil
    - name: 'npm: install js-beautify'
      npm: name=js-beautify executable=~/.anyenv/envs/ndenv/shims/npm global=yes state=latest
    - name: 'npm: install git-fire'
      npm: name=git-fire executable=~/.anyenv/envs/ndenv/shims/npm global=yes state=latest
    - name: 'Tap homebrew repositories'
      homebrew_tap: tap={{ item }} state=present
      with_items: 
        - caskroom/cask
        - caskroom/versions
        - caskroom/homebrew-fonts
        - homebrew/versions
        - sanemat/font
        - supistar/customs
    - name: 'homebrew: update'
      command: brew update

  tasks:
    - name: 'Install Homebrew cask packages'
      homebrew_cask: name={{ item }}
      with_items:
        - xquartz
        - adobe-air
        - adobe-creative-cloud
        - air-video-server-hd
        - alfred
        - android-studio
        - appcode
        - arduino
        - burn
        - chromecast
        - chromium
        - cooviewer
        - dropbox
        - duet
        - eclipse-ide
        - eye-fi
        - firefox
        - font-m-plus
        - font-terminus
        - genymotion
        - google-chrome
        - handbrake
        - hipchat
        - horndis
        - inkscape
        - intellij-idea-ce
        - iterm2
        - java
        - java6
        - java7
        - karabiner
        - kobito
        - kindle
        - lastfm
        - limechat
        - macvim-kaoriya
        - mono-mdk
        - mono-mdk3121
        - playonmac
        - pycharm-ce
        - skitch
        - skype
        - slack
        - splashtop-personal
        - sublime-text
        - unity463p2
        - vagrant
        - virtualbox
        - visual-studio-code
        - vlc
        - vmware-fusion
        - webstorm
        - xamarin-studio
    - name: 'Install Homebrew packages'
      homebrew: name={{ item }} state=latest
      with_items:
        - gcc
        - android-sdk
        - android-ndk
        - ant
        - apktool
        - appledoc22
        - autoconf
        - automake
        - chromedriver
        - cmake
        - ctags
        - curl
        - doxygen
        - expat
        - faac
        - fswatch
        - git
        - git-flow
        - gnupg
        - go
        - gradle
        - heroku-toolbelt
        - highlight
        - httpie
        - hub
        - icu4c
        - imagemagick
        - ino
        - ios-sim
        - jq
        - jsdoc-toolkit
        - lame
        - libevent
        - libpng
        - libtool
        - libusb
        - libusb-compat
        - libxml2
        - libyaml
        - maven
        - nkf
        - phantomjs
        - pkg-config
        - psutils
        - reattach-to-user-namespace
        - redis
        - rmtrash
        - source-highlight
        - sqlite
        - swig
        - tig
        - tmux2
        - tree
        - watch
        - wget
        - wine
        - winetricks
        - x264
        - xctool
        - xvid
        - yasm
        - yuicompressor
        - z
        - zsh
        - zsh-completions
    - name: 'Install Homebrew packages: ffmpeg'
      homebrew: name=ffmpeg state=latest install_options=with-faac
    - name: 'Install Homebrew packages: ricty'
      homebrew: name=ricty state=latest install_options=powerline,vim-powerline
    - name: 'Clone dotfiles under home dir'
      command: homesick clone supistar/dotfiles
    - name: 'Pull homesick dotfiles'
      command: homesick pull dotfiles
    - name: 'Make symlinks to under home dir'
      command: homesick symlink dotfiles --force
    - name: 'Copy Ricty fonts'
      shell: cp -f /usr/local/opt/ricty/share/fonts/Ricty*.ttf ~/Library/Fonts/
    - name: 'Clone powerline fonts'
      command: git clone git@github.com:powerline/fonts.git /tmp/fonts
    - name: 'Install powerline fonts'
      command: sh /tmp/fonts/install.sh
    - name: 'Refresh fonts cache'
      command: fc-cache -vf
    - name: 'Delete temporary directory for powerline fonts'
      file: path=/tmp/fonts state=absent
    - name: 'mkdir Karabiner dir'
      file: path="~/Library/Application Support/Karabiner" state=directory
    - name: 'Karabiner: Make symlink of setting files'
      file: src={{ item }} dest="~/Library/Application Support/Karabiner/{{ item | basename }}" state=link force=yes
      with_fileglob:
        - ~/.homesick/repos/dotfiles/applications/Karabiner/*
    - name: 'mkdir vim backup dir'
      file: path=~/.vim/backup state=directory
    - name: 'mkdir vim-neobundle dir'
      file: path=~/.vim/bundle state=directory
      notify: install neobundle
    - name: 'mkdir vim undo dir'
      file: path=~/.vim/undo state=directory

  handlers:
    - name: 'install neobundle'
      command: git clone git://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim

