---
- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars:
    locale: ja_JP.UTF-8
    zone: Asia/Tokyo
    zoneinfo_path: /usr/share/zoneinfo/Asia/Tokyo

  pre_tasks:
    - name: 'Install gem packages'
      gem: name={{ item }} executable=~/.anyenv/envs/rbenv/shims/gem user_install=False
      with_items:
        - bundler
        - homesick
        - gisty
    - name: 'Update pip'
      pip: name=pip executable=~/.anyenv/envs/pyenv/shims/pip2.7 state=latest
    - name: 'Install python packages'
      pip: name={{ item }} executable=~/.anyenv/envs/pyenv/shims/pip2.7 extra_args="--user" state=latest
      with_items:
        - powerline-status
        - psutil
    - name: 'Install node packages'
      npm: name={{ item }} executable=~/.anyenv/envs/ndenv/shims/npm global=yes state=latest
      with_items:
        - js-beautify
        - git-fire

  tasks:
    - name: 'Install essential packages'
      yum: name={{ item }} enablerepo=epel state=latest
      sudo: yes
      with_items:
        - gitflow
        - tmux
    - name: 'Clone dotfiles under home dir'
      command: homesick clone supistar/dotfiles
    - name: 'Pull homesick dotfiles'
      command: homesick pull dotfiles
    - name: 'Make symlinks to under home dir'
      command: homesick symlink dotfiles --force
    - name: 'mkdir vim related directories'
      file: path={{ item }} state=directory
      notify: install neobundle
      with_items:
        - ~/.vim/backup
        - ~/.vim/bundle
        - ~/.vim/undo

  handlers:
    - name: 'install neobundle'
      command: git clone git://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim

