---
- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars:

    homebrew_packages_taps:
      - sanemat/font

    homebrew_packages_packages:
      - { name: gcc }
      - { name: android-sdk }
      - { name: android-ndk }
      - { name: ant }
      - { name: apktool }
      - { name: appledoc22 }
      - { name: autoconf }
      - { name: automake }
      - { name: chromedriver }
      - { name: cmake }
      - { name: ctags }
      - { name: curl }
      - { name: doxygen }
      - { name: expat }
      - { name: fswatch }
      - { name: git }
      - { name: git-flow }
      - { name: go }
      - { name: gradle }
      - { name: highlight }
      - { name: httpie }
      - { name: hub }
      - { name: ios-sim }
      - { name: jq }
      - { name: jsdoc-toolkit }
      - { name: libevent }
      - { name: libpng }
      - { name: libtool }
      - { name: libusb }
      - { name: libusb-compat }
      - { name: libxml2 }
      - { name: libyaml }
      - { name: maven }
      - { name: nkf }
      - { name: phantomjs }
      - { name: pkg-config }
      - { name: psutils }
      - { name: reattach-to-user-namespace }
      - { name: redis }
      - { name: ricty, install_options: powerline, vim-powerline }
      - { name: rmtrash }
      - { name: source-highlight }
      - { name: sqlite }
      - { name: swig }
      - { name: tig }
      - { name: tmux2 }
      - { name: tree }
      - { name: watch }
      - { name: wget }
      - { name: wine }
      - { name: winetricks }
      - { name: xctool }
      - { name: z }
      - { name: zsh }
      - { name: zsh-completions }

    homebrew_cask_packages_packages:
      - xquartz
      - alfred
      - android-studio
      - firefox
      - font-m-plus
      - font-terminus
      - google-chrome
      - iterm2
      - java
      - java6
      - java7
      - karabiner
      - macvim-kaoriya
      - sublime-text
      - vagrant
      - virtualbox

  pre_tasks:
    - name: 'gem: install bundler'
      gem: name=bundler executable=~/.anyenv/envs/rbenv/shims/gem user_install=False
    - name: 'gem: install homesick'
      gem: name=homesick executable=~/.anyenv/envs/rbenv/shims/gem user_install=False
    - name: 'gem: install cocoapods'
      gem: name=cocoapods executable=~/.anyenv/envs/rbenv/shims/gem user_install=False
    - name: 'gem: install gisty'
      gem: name=gisty executable=~/.anyenv/envs/rbenv/shims/gem user_install=False
    - name: 'pip: update pip'
      command: ~/.anyenv/envs/pyenv/shims/pip2.7 install --upgrade pip
    - name: 'pip: install powerline'
      command: ~/.anyenv/envs/pyenv/shims/pip2.7 install --user powerline-status
    - name: 'pip: install psutil'
      command: ~/.anyenv/envs/pyenv/shims/pip2.7 install --user psutil
    - name: 'npm: install js-beautify'
      npm: name=js-beautify executable=~/.anyenv/envs/ndenv/shims/npm global=yes state=latest
    - name: 'npm: install git-fire'
      npm: name=git-fire executable=~/.anyenv/envs/ndenv/shims/npm global=yes state=latest
    - name: 'homebrew: tap homebrew/versions'
      command: brew tap homebrew/versions
    - name: 'homebrew: tap caskroom/versions'
      command: brew tap caskroom/versions
    - name: 'homebrew: tap caskroom/homebrew-fonts'
      command: brew tap caskroom/homebrew-fonts
    - name: 'homebrew: tap supistar/customs'
      command: brew tap supistar/customs
    - name: 'homebrew: update'
      command: brew update

  tasks:
    - name: 'Clone dotfiles under home dir'
      command: homesick clone supistar/dotfiles
    - name: 'Pull homesick dotfiles'
      command: homesick pull dotfiles
    - name: 'Make symlinks to under home dir'
      command: homesick symlink dotfiles --force
    - name: 'Copy Ricty fonts'
      shell: cp -f /usr/local/opt/ricty/share/fonts/Ricty*.ttf ~/Library/Fonts/
    - name: 'Clone powerline fonts'
      command: git clone git@github.com:powerline/fonts.git /tmp/fonts
    - name: 'Install powerline fonts'
      command: sh /tmp/fonts/install.sh
    - name: 'Refresh fonts cache'
      command: fc-cache -vf
    - name: 'Delete temporary directory for powerline fonts'
      file: path=/tmp/fonts state=absent
    - name: 'mkdir Karabiner dir'
      file: path="~/Library/Application Support/Karabiner" state=directory
    - name: 'Karabiner: Make symlink of setting files'
      file: src={{ item }} dest="~/Library/Application Support/Karabiner/{{ item | basename }}" state=link force=yes
      with_fileglob:
        - ~/.homesick/repos/dotfiles/applications/Karabiner/*
    - name: 'mkdir vim backup dir'
      file: path=~/.vim/backup state=directory
    - name: 'mkdir vim-neobundle dir'
      file: path=~/.vim/bundle state=directory
      notify: install neobundle
    - name: 'mkdir vim undo dir'
      file: path=~/.vim/undo state=directory

  handlers:
    - name: 'install neobundle'
      command: git clone git://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim

  roles:
    - hnakamur.homebrew-cask-packages
    - hnakamur.homebrew-packages
